export const dynamic = "force-dynamic";

import Link from "next/link";
import GlassShell from "@/features/shopreel/ui/system/GlassShell";
import GenerateCalendarButton from "@/features/shopreel/calendar/components/GenerateCalendarButton";
import { createAdminClient } from "@/lib/supabase/server";
import { getCurrentShopId } from "@/features/shopreel/server/getCurrentShopId";
import { ShopReelActionRail, ShopReelEmptyState, ShopReelPageHero, ShopReelSurface } from "@/features/shopreel/ui/system/ShopReelPagePrimitives";
const WEEK_DAYS = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
const WINDOWS = ["8:30 AM","12:15 PM","5:40 PM"];
export default async function ShopReelCalendarPage(){const shopId=await getCurrentShopId();const supabase=createAdminClient();const legacy=supabase as unknown as {from:(table:string)=>any};const {data:calendar}=await legacy.from("content_calendars").select("id").or(`tenant_shop_id.eq.${shopId},source_shop_id.eq.${shopId}`).order("created_at",{ascending:false}).limit(1).maybeSingle();let hasItems=false;if(calendar?.id){const {data}=await legacy.from("content_calendar_items").select("id").eq("calendar_id",calendar.id).limit(1);hasItems=(data??[]).length>0;}return <GlassShell title="Calendar" hidePageIntro><div className="space-y-4"><ShopReelPageHero title="Calendar" subtitle="Plan upcoming posts, campaigns, and publishing windows." actions={[{label:"Generate calendar",href:"#",primary:true},{label:"Create content",href:"/shopreel/create"}]}/><div className="hidden"><GenerateCalendarButton/></div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-4"><ShopReelSurface title="7-day planning board" description="Planning slots only — these are not published posts."><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{WEEK_DAYS.map((d)=><div key={d} className="rounded-xl border border-white/10 bg-black/25 p-3"><div className="text-xs font-medium text-white/80">{d}</div><div className="mt-2 rounded-lg border border-dashed border-white/20 p-3 text-xs text-white/50">Open planning slot</div></div>)}</div></ShopReelSurface>{!hasItems&&<ShopReelEmptyState title="No scheduled content yet" description="Generate a calendar from projects or create content first."/>}</div><ShopReelActionRail title="Recommended posting windows" items={WINDOWS.map((w)=>`${w} local audience window`)} /></div></div></GlassShell>}
