import { createAdminClient } from "@/lib/supabase/server";
import type { DiscoveredGrowthFeature, GrowthCampaignType, GrowthDraftStatus, GrowthPlatform, GrowthRunStatus } from "./types";
import { buildCampaignObjective, buildCampaignTitle, platformsOrDefault } from "./campaignPlanner";
import { buildDraftSeeds } from "./draftGenerator";

function db() { return createAdminClient() as unknown as { from: (table: string) => any }; }

export async function createRun(createdBy: string, status: GrowthRunStatus) { const { data, error } = await db().from("internal_growth_agent_runs").insert({ created_by: createdBy, status, source_type: "code_scan" }).select("*").single(); if (error) throw error; return data as { id: string }; }
export async function completeRun(runId: string, status: GrowthRunStatus, summary: string, errorMessage?: string) { const payload: { status: GrowthRunStatus; summary: string; error_message?: string } = { status, summary }; if (errorMessage) payload.error_message = errorMessage; await db().from("internal_growth_agent_runs").update(payload).eq("id", runId); }
export async function upsertFeatures(features: DiscoveredGrowthFeature[], runId: string) { const rows = features.map((feature) => ({ run_id: runId, feature_key: feature.featureKey, title: feature.title, description: feature.description, route_path: feature.routePath, source_files: feature.sourceFiles, audience: feature.audience, value_props: feature.valueProps, launch_angle: feature.launchAngle })); const { data, error } = await db().from("internal_growth_features").upsert(rows, { onConflict: "feature_key" }).select("*"); if (error) throw error; return (data ?? []) as Array<{ id: string }>; }
export async function updateFeatureStatus(id: string, status: "approved" | "ignored") { const { data, error } = await db().from("internal_growth_features").update({ status }).eq("id", id).select("*").single(); if (error) throw error; return data; }
export async function generateCampaign(featureId: string, campaignType: GrowthCampaignType, targetPlatforms: GrowthPlatform[]) { const { data: feature, error: featureError } = await db().from("internal_growth_features").select("*").eq("id", featureId).single(); if (featureError) throw featureError; const platforms = platformsOrDefault(targetPlatforms); const { data: campaign, error: campaignError } = await db().from("internal_growth_campaigns").insert({ feature_id: featureId, title: buildCampaignTitle(feature.title as string, campaignType), campaign_type: campaignType, objective: buildCampaignObjective(feature.title as string), target_platforms: platforms, status: "draft" }).select("*").single(); if (campaignError) throw campaignError; const seeds = buildDraftSeeds(feature.title as string, feature.description as string, platforms); const { data: drafts, error: draftsError } = await db().from("internal_growth_drafts").insert(seeds.map((seed) => ({ campaign_id: campaign.id, platform: seed.platform, format: seed.format, title: seed.title, body: seed.body, hook: seed.hook, cta: seed.cta, status: "draft" }))).select("*"); if (draftsError) throw draftsError; return { campaign, drafts }; }
export async function updateDraft(id: string, patch: { title?: string; body?: string; hook?: string | null; cta?: string | null; status?: GrowthDraftStatus }) { const { data, error } = await db().from("internal_growth_drafts").update(patch).eq("id", id).select("*").single(); if (error) throw error; return data; }
export async function overview() { const [runs, features, campaigns, drafts] = await Promise.all([db().from("internal_growth_agent_runs").select("*").order("created_at", { ascending: false }).limit(10), db().from("internal_growth_features").select("*").order("updated_at", { ascending: false }).limit(100), db().from("internal_growth_campaigns").select("*").order("updated_at", { ascending: false }).limit(100), db().from("internal_growth_drafts").select("*").order("updated_at", { ascending: false }).limit(300)]); return { runs: runs.data ?? [], features: features.data ?? [], campaigns: campaigns.data ?? [], drafts: drafts.data ?? [] }; }
