import type { OperatorWorldKind } from "@/features/shopreel/operator/operatorWorlds";

export type RuntimeWorldId =
  | "campaign"
  | "idea"
  | "upload"
  | "asset_library"
  | "generation"
  | "video_creation"
  | "review"
  | "render"
  | "publish"
  | "calendar"
  | "analytics"
  | "automation"
  | "operations";

export type RuntimeWorldCategory = "core" | "support" | "utility" | "internal";
export type RuntimeWorldAtmosphere = { tone: string; intensity: "low"|"medium"|"high"; accent: string; backgroundSeed: string; visualMotif: string };
export type RuntimeWorldAction = { id: string; label: string; href?: string };
export type RuntimeWorldDataContract = { key: string; required: boolean; description: string };
export type RuntimeWorldTransition = { reason: string; toWorldId: RuntimeWorldId };
export type RuntimeWorldEntryIntent = {
  worldId: RuntimeWorldId;
  entityKind?: OperatorWorldKind | string | null;
  entityId?: string | null;
  href?: string;
  recommendedAction?: string | null;
  fallbackRoute: string;
  source: "home_deck" | "command" | "direct";
};

export type RuntimeWorldDefinition = {
  worldId: RuntimeWorldId; label: string; shortLabel: string; category: RuntimeWorldCategory;
  canonicalRoute: string; alternateRoutes: string[]; supportedEntityKinds: string[]; goal: string;
  primaryActions: RuntimeWorldAction[]; yesNoEligible: boolean; deckVisible: boolean;
  requiredDataContracts: RuntimeWorldDataContract[]; commonBlockers: string[]; nextWorldIds: RuntimeWorldId[];
  fallbackWorldId: RuntimeWorldId; atmosphere: RuntimeWorldAtmosphere;
  operatorCopy: { entryLabel: string; objectiveTemplate: string; nextActionTemplate: string; emptyState: string };
};

export const RUNTIME_WORLD_MAP: Record<RuntimeWorldId, RuntimeWorldDefinition> = {
  campaign: { worldId:"campaign",label:"Campaign World",shortLabel:"Campaign",category:"core",canonicalRoute:"/shopreel/campaigns",alternateRoutes:["/shopreel/campaigns/new"],supportedEntityKinds:["campaign"],goal:"Plan and advance campaigns.",primaryActions:[{id:"open_campaign",label:"Open campaign",href:"/shopreel/campaigns"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"campaign.id",required:true,description:"Campaign identifier"}],commonBlockers:["Missing brief","Awaiting approvals"],nextWorldIds:["generation","review"],fallbackWorldId:"operations",atmosphere:{tone:"strategic",intensity:"medium",accent:"violet",backgroundSeed:"campaign-grid",visualMotif:"tracks"},operatorCopy:{entryLabel:"Enter Campaign World",objectiveTemplate:"Advance campaign {entityId}",nextActionTemplate:"Continue campaign planning",emptyState:"No campaigns yet. Start a campaign to enter this world."}},
  idea:{ worldId:"idea",label:"Idea World",shortLabel:"Ideas",category:"core",canonicalRoute:"/shopreel/ideas",alternateRoutes:["/shopreel/opportunities"],supportedEntityKinds:["opportunity"],goal:"Capture and refine ideas.",primaryActions:[{id:"open_ideas",label:"Open ideas",href:"/shopreel/ideas"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"opportunity.id",required:false,description:"Opportunity identifier"}],commonBlockers:["No opportunity source"],nextWorldIds:["campaign","generation"],fallbackWorldId:"operations",atmosphere:{tone:"exploratory",intensity:"low",accent:"amber",backgroundSeed:"idea-pulse",visualMotif:"nodes"},operatorCopy:{entryLabel:"Enter Idea World",objectiveTemplate:"Clarify next idea",nextActionTemplate:"Move idea into campaign",emptyState:"No ideas found. Create or import an opportunity."}},
  upload:{ worldId:"upload",label:"Upload World",shortLabel:"Upload",category:"support",canonicalRoute:"/shopreel/upload",alternateRoutes:[],supportedEntityKinds:["manual_asset"],goal:"Ingest source assets.",primaryActions:[{id:"upload_assets",label:"Upload assets",href:"/shopreel/upload"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"asset.files",required:true,description:"One or more asset files"}],commonBlockers:["No files selected"],nextWorldIds:["asset_library"],fallbackWorldId:"operations",atmosphere:{tone:"intake",intensity:"medium",accent:"cyan",backgroundSeed:"upload-stream",visualMotif:"ingress"},operatorCopy:{entryLabel:"Enter Upload World",objectiveTemplate:"Bring assets into runtime",nextActionTemplate:"Route uploaded assets to library",emptyState:"No recent uploads. Add assets to continue."}},
  asset_library:{ worldId:"asset_library",label:"Asset Library World",shortLabel:"Library",category:"support",canonicalRoute:"/shopreel/library",alternateRoutes:[],supportedEntityKinds:["manual_asset"],goal:"Organize and select assets.",primaryActions:[{id:"open_library",label:"Open library",href:"/shopreel/library"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"asset.id",required:false,description:"Selected asset id"}],commonBlockers:["No tagged assets"],nextWorldIds:["generation"],fallbackWorldId:"upload",atmosphere:{tone:"organizing",intensity:"low",accent:"teal",backgroundSeed:"library-grid",visualMotif:"shelves"},operatorCopy:{entryLabel:"Enter Library World",objectiveTemplate:"Prepare assets for generation",nextActionTemplate:"Select assets and continue",emptyState:"Library is empty. Upload assets first."}},
  generation:{ worldId:"generation",label:"Generation World",shortLabel:"Generate",category:"core",canonicalRoute:"/shopreel/generations",alternateRoutes:[],supportedEntityKinds:["generation","campaign"],goal:"Generate content outputs.",primaryActions:[{id:"open_generations",label:"Open generations",href:"/shopreel/generations"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"generation.id",required:false,description:"Generation id"}],commonBlockers:["Missing prompt","No source context"],nextWorldIds:["review"],fallbackWorldId:"campaign",atmosphere:{tone:"creative",intensity:"high",accent:"fuchsia",backgroundSeed:"gen-wave",visualMotif:"flow"},operatorCopy:{entryLabel:"Enter Generation World",objectiveTemplate:"Produce output from selected context",nextActionTemplate:"Send output to review",emptyState:"No generations yet. Start from campaign or idea."}},
  video_creation:{ worldId:"video_creation",label:"Video Creation World",shortLabel:"Video",category:"core",canonicalRoute:"/shopreel/video-creation",alternateRoutes:["/shopreel/video-creation/advanced"],supportedEntityKinds:["render_job","content_piece"],goal:"Create and refine video work.",primaryActions:[{id:"open_video_creation",label:"Open video creation",href:"/shopreel/video-creation"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"project.id",required:false,description:"Video project id"}],commonBlockers:["No script ready"],nextWorldIds:["review"],fallbackWorldId:"generation",atmosphere:{tone:"production",intensity:"high",accent:"orange",backgroundSeed:"timeline",visualMotif:"frames"},operatorCopy:{entryLabel:"Enter Video Creation World",objectiveTemplate:"Advance video build",nextActionTemplate:"Move video to review",emptyState:"No active video projects."}},
  review:{ worldId:"review",label:"Review World",shortLabel:"Review",category:"core",canonicalRoute:"/shopreel/review",alternateRoutes:[],supportedEntityKinds:["review_item","generation","content_piece"],goal:"Approve or request revisions.",primaryActions:[{id:"open_review",label:"Open review",href:"/shopreel/review"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"review.status",required:true,description:"Review status"}],commonBlockers:["Missing reviewer decision"],nextWorldIds:["render","generation"],fallbackWorldId:"operations",atmosphere:{tone:"critical",intensity:"medium",accent:"indigo",backgroundSeed:"review-lens",visualMotif:"checkpoints"},operatorCopy:{entryLabel:"Enter Review World",objectiveTemplate:"Resolve approval state",nextActionTemplate:"Approve then render",emptyState:"Nothing awaiting review right now."}},
  render:{ worldId:"render",label:"Render World",shortLabel:"Render",category:"core",canonicalRoute:"/shopreel/render-queue",alternateRoutes:["/shopreel/render-jobs"],supportedEntityKinds:["render_job"],goal:"Run and monitor renders.",primaryActions:[{id:"open_render_queue",label:"Open render queue",href:"/shopreel/render-queue"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"render_job.id",required:false,description:"Render job id"}],commonBlockers:["Render failure","Queue backlog"],nextWorldIds:["publish"],fallbackWorldId:"review",atmosphere:{tone:"throughput",intensity:"high",accent:"red",backgroundSeed:"render-pipeline",visualMotif:"conveyor"},operatorCopy:{entryLabel:"Enter Render World",objectiveTemplate:"Complete pending renders",nextActionTemplate:"Send completed render to publish",emptyState:"No render jobs found."}},
  publish:{ worldId:"publish",label:"Publish World",shortLabel:"Publish",category:"core",canonicalRoute:"/shopreel/publish-center",alternateRoutes:["/shopreel/publish-queue"],supportedEntityKinds:["publication","content_piece"],goal:"Publish or stage distribution.",primaryActions:[{id:"open_publish",label:"Open publish center",href:"/shopreel/publish-center"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"publication.status",required:true,description:"Publish status"}],commonBlockers:["Channel not configured"],nextWorldIds:["calendar","analytics"],fallbackWorldId:"render",atmosphere:{tone:"distribution",intensity:"medium",accent:"emerald",backgroundSeed:"publish-grid",visualMotif:"broadcast"},operatorCopy:{entryLabel:"Enter Publish World",objectiveTemplate:"Publish approved output",nextActionTemplate:"Publish now or schedule",emptyState:"No publish-ready outputs."}},
  calendar:{ worldId:"calendar",label:"Calendar World",shortLabel:"Calendar",category:"support",canonicalRoute:"/shopreel/calendar",alternateRoutes:[],supportedEntityKinds:["calendar_item","publication"],goal:"Schedule and sequence releases.",primaryActions:[{id:"open_calendar",label:"Open calendar",href:"/shopreel/calendar"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"schedule.at",required:false,description:"Scheduled datetime"}],commonBlockers:["No schedule window"],nextWorldIds:["analytics"],fallbackWorldId:"publish",atmosphere:{tone:"timing",intensity:"low",accent:"sky",backgroundSeed:"calendar-orbit",visualMotif:"rings"},operatorCopy:{entryLabel:"Enter Calendar World",objectiveTemplate:"Place work on schedule",nextActionTemplate:"Confirm planned publish",emptyState:"No scheduled items yet."}},
  analytics:{ worldId:"analytics",label:"Analytics World",shortLabel:"Analytics",category:"support",canonicalRoute:"/shopreel/analytics",alternateRoutes:[],supportedEntityKinds:["publication","campaign"],goal:"Measure and feed insights back.",primaryActions:[{id:"open_analytics",label:"Open analytics",href:"/shopreel/analytics"}],yesNoEligible:true,deckVisible:true,requiredDataContracts:[{key:"publication.id",required:false,description:"Published entity reference"}],commonBlockers:["No published baseline"],nextWorldIds:["idea"],fallbackWorldId:"operations",atmosphere:{tone:"reflective",intensity:"medium",accent:"blue",backgroundSeed:"metrics-constellation",visualMotif:"signals"},operatorCopy:{entryLabel:"Enter Analytics World",objectiveTemplate:"Review outcome and learnings",nextActionTemplate:"Feed insights into next ideas",emptyState:"Analytics will appear after publish activity."}},
  automation:{ worldId:"automation",label:"Automation World",shortLabel:"Automation",category:"utility",canonicalRoute:"/shopreel/automation",alternateRoutes:[],supportedEntityKinds:["campaign","publication"],goal:"Configure automation controls.",primaryActions:[{id:"open_automation",label:"Open automation",href:"/shopreel/automation"}],yesNoEligible:false,deckVisible:true,requiredDataContracts:[{key:"automation.rules",required:false,description:"Automation rule set"}],commonBlockers:["No rule configuration"],nextWorldIds:["operations"],fallbackWorldId:"operations",atmosphere:{tone:"systems",intensity:"medium",accent:"slate",backgroundSeed:"automation-lattice",visualMotif:"circuits"},operatorCopy:{entryLabel:"Enter Automation World",objectiveTemplate:"Tune lifecycle automation",nextActionTemplate:"Route issues to operations",emptyState:"No automation rules active."}},
  operations:{ worldId:"operations",label:"Operations World",shortLabel:"Ops",category:"internal",canonicalRoute:"/shopreel/operations",alternateRoutes:["/shopreel/operator"],supportedEntityKinds:["campaign","generation","render_job","publication","opportunity"],goal:"Resolve blockers and recover flow.",primaryActions:[{id:"open_operations",label:"Open operations",href:"/shopreel/operations"}],yesNoEligible:false,deckVisible:true,requiredDataContracts:[{key:"blockers",required:false,description:"Actionable blocker list"}],commonBlockers:["Unknown runtime context"],nextWorldIds:["idea","campaign","generation","review","render","publish","calendar","analytics","automation","upload","asset_library","video_creation"],fallbackWorldId:"operations",atmosphere:{tone:"control",intensity:"high",accent:"zinc",backgroundSeed:"ops-matrix",visualMotif:"console"},operatorCopy:{entryLabel:"Enter Operations World",objectiveTemplate:"Stabilize runtime flow",nextActionTemplate:"Resolve blockers and resume world",emptyState:"No active blockers. Continue from recent world."}},
};
