export const dynamic = "force-dynamic";
import Link from "next/link";
import { createAdminClient } from "@/lib/supabase/server";
import { requireShopId } from "@/features/shopreel/server/requireShopId";
import { mapExportPackage } from "@/features/shopreel/export/exportPackage";
import GlassShell from "@/features/shopreel/ui/system/GlassShell";
import { ShopReelActionRail, ShopReelEmptyState, ShopReelPageHero, ShopReelSurface } from "@/features/shopreel/ui/system/ShopReelPagePrimitives";
const TYPES=["Video exports","Caption packs","Thumbnail assets","Blog drafts","Campaign bundles"];
export default async function ShopReelDownloadsPage(){const shopId=await requireShopId();const supabase=createAdminClient();const {data}=await supabase.from("shopreel_export_packages").select("*").eq("shop_id",shopId).order("created_at",{ascending:false}).limit(100);const items=(data??[]).map(mapExportPackage);return <GlassShell title="Downloads" hidePageIntro><div className="space-y-4"><ShopReelPageHero title="Downloads" subtitle="Export-ready packages and files appear here after projects are processed." actions={[{label:"Create content",href:"/shopreel/create",primary:true},{label:"Open processing",href:"/shopreel/render-jobs"}]}/><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-4"><ShopReelSurface title="Package types"><div className="grid gap-2 sm:grid-cols-2">{TYPES.map((t)=><div key={t} className="rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-sm text-white/80">{t}</div>)}</div></ShopReelSurface><ShopReelSurface title="Export packages">{items.length===0?<ShopReelEmptyState title="No downloads yet" description="Process a draft to create your first export package."/>:<div className="grid gap-2">{items.map((pkg)=><div key={pkg.id} className="rounded-xl border border-white/10 bg-white/[0.02] p-3 text-sm text-white/80">Package {pkg.id.slice(0,8)} · {pkg.status}</div>)}</div>}</ShopReelSurface></div><ShopReelActionRail title="Export package includes" items={["Primary video file(s)","Caption text and hashtag set","Thumbnail assets","Channel checklist and bundle notes"]}/></div></div></GlassShell>}
