"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import GlassCard from "@/features/shopreel/ui/system/GlassCard";
import GlassButton from "@/features/shopreel/ui/system/GlassButton";
import GlassInput from "@/features/shopreel/ui/system/GlassInput";
import GlassTextarea from "@/features/shopreel/ui/system/GlassTextarea";
import GlassBadge from "@/features/shopreel/ui/system/GlassBadge";
import { cx, glassTheme } from "@/features/shopreel/ui/system/glassTheme";
import MediaBin, { type MediaBinItem } from "@/features/shopreel/editor/components/MediaBin";
import TimelineLane from "@/features/shopreel/editor/components/TimelineLane";
import TimelineRuler from "@/features/shopreel/editor/components/TimelineRuler";
import { buildTimelineClips, draftDurationMs, formatSecondsLabel, PX_PER_SECOND, type TimelineSelection } from "@/features/shopreel/editor/lib/timeline";
import { buildEditorSessionFromDraft, type EditorVariant } from "@/features/shopreel/editor/lib/session";
import { applyEditorCommand, summarizeCommand, type CommandState, type EditorCommand } from "@/features/shopreel/editor/lib/commands";
import { buildPersistedEditorSession, reorderScenesByPersistedOrder, type PersistedEditorSession } from "@/features/shopreel/editor/lib/sessionPersistence";
import { runEditorPreflight } from "@/features/shopreel/editor/lib/preflight";
import type { StoryDraft } from "@/features/shopreel/story-builder/types";
import { CinematicPreviewStage, EditorWorkspaceFrame, InspectorRail, PlatformPreviewCard, ProductionTopBar, RenderReadinessRail, SceneSequenceCard, SequenceTimeline, SourceMediaRail } from "./EditorStudioPrimitives";

type Props = { generationId: string; initialDraft: StoryDraft; initialStatus: string; initialRenderUrl: string | null; mediaItems: MediaBinItem[]; persistedEditorSession: PersistedEditorSession | null; };
const clone = <T,>(v:T)=> JSON.parse(JSON.stringify(v)) as T;
const syncDraft = (draft: StoryDraft): StoryDraft => ({ ...draft, targetDurationSeconds: draft.scenes.reduce((s,sc)=> s+Math.max(1,Number(sc.durationSeconds??0)),0) });

export default function EditorClient(props: Props) {
 const router=useRouter(); const search=useSearchParams();
 const [draft,setDraft]=useState(()=>{const d=clone(props.initialDraft); d.scenes=reorderScenesByPersistedOrder(d.scenes, props.persistedEditorSession); return syncDraft(d);});
 const [selection,setSelection]=useState<TimelineSelection>(()=>{const id=search.get("scene"); return id?{type:"scene",id}:null;});
 const [variants,setVariants]=useState<EditorVariant[]>(props.persistedEditorSession?.variants??[]); const [activeVariantId,setActiveVariantId]=useState<string|null>(props.persistedEditorSession?.variants[0]?.id??null);
 const [commandHistory,setCommandHistory]=useState<EditorCommand[]>([]); const [historyStack,setHistoryStack]=useState<CommandState[]>([{draft,variants,activeSceneId:null,activeVariantId}]); const [historyPointer,setHistoryPointer]=useState(0);
 const [saveState,setSaveState]=useState<"saved"|"unsaved"|"saving"|"failed">("saved"); const [isSaving,setIsSaving]=useState(false); const [isRendering,setIsRendering]=useState(false); const [error,setError]=useState<string|null>(null);
 const timer=useRef<number|null>(null);
 const clips=useMemo(()=>buildTimelineClips(draft),[draft]); const selectedScene = useMemo(()=> draft.scenes.find(s=>s.id===selection?.id)??draft.scenes[0]??null,[draft.scenes,selection]);
 const selectedClip=useMemo(()=> selection?.type==="clip"?clips.find(c=>c.id===selection.id)??null:null,[selection,clips]); const preflight=useMemo(()=>runEditorPreflight(draft, variants.find(v=>v.id===activeVariantId)??null),[draft,variants,activeVariantId]);
 const totalMs=draftDurationMs(draft); const editorSession=buildEditorSessionFromDraft(props.generationId,draft);
 const execCommand=(payload: Parameters<typeof applyEditorCommand>[1])=>{const s:CommandState={draft,variants,activeSceneId:selectedScene?.id??null,activeVariantId}; const a=applyEditorCommand(s,payload,editorSession.id); setDraft(syncDraft(a.nextState.draft)); setVariants(a.nextState.variants); setActiveVariantId(a.nextState.activeVariantId); setSelection(a.nextState.activeSceneId?{type:"scene",id:a.nextState.activeSceneId}:selection); setCommandHistory(p=>[...p.slice(-49),a.command]); setHistoryStack(p=>[...p.slice(0,historyPointer+1),a.nextState].slice(-50)); setHistoryPointer(p=>Math.min(49,p+1)); setSaveState("unsaved");};

 const undoCommand=()=>{if(historyPointer<=0)return; const prev=historyStack[historyPointer-1]; if(!prev)return; setDraft(syncDraft(prev.draft)); setVariants(prev.variants); setActiveVariantId(prev.activeVariantId); setSelection(prev.activeSceneId?{type:"scene",id:prev.activeSceneId}:null); setHistoryPointer(historyPointer-1); setSaveState("unsaved");};
 const redoCommand=()=>{const nxt=historyStack[historyPointer+1]; if(!nxt)return; setDraft(syncDraft(nxt.draft)); setVariants(nxt.variants); setActiveVariantId(nxt.activeVariantId); setSelection(nxt.activeSceneId?{type:"scene",id:nxt.activeSceneId}:null); setHistoryPointer(historyPointer+1); setSaveState("unsaved");};
 const saveDraft=async()=>{try{setIsSaving(true); setSaveState("saving"); const res=await fetch(`/api/shopreel/story-generations/${props.generationId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({storyDraft:draft})}); const j=await res.json(); if(!res.ok||!j.ok) throw new Error(j.error??"Failed"); await fetch(`/api/shopreel/story-generations/${props.generationId}/editor-session`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({editorSession:buildPersistedEditorSession(draft,variants)})}); setSaveState("saved"); router.refresh(); }catch(e){setError(e instanceof Error?e.message:"Failed"); setSaveState("failed");}finally{setIsSaving(false)}};
 const renderAgain=async()=>{try{setIsRendering(true); if(preflight.status==="blocked") throw new Error(preflight.blockers.map(b=>b.message).join("; ")); await saveDraft(); const res=await fetch(`/api/shopreel/story-generations/${props.generationId}/render`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({preflight})}); const j=await res.json(); if(!res.ok||!j.ok) throw new Error(j.error??"Failed");}catch(e){setError(e instanceof Error?e.message:"Failed");}finally{setIsRendering(false)}};
 useEffect(()=>{if(saveState!=="unsaved") return; if(timer.current) window.clearTimeout(timer.current); timer.current=window.setTimeout(()=>{void saveDraft();},1200); return ()=>{if(timer.current) window.clearTimeout(timer.current);};},[draft,variants,saveState]);

 return <EditorWorkspaceFrame
  topBar={<ProductionTopBar title={draft.title||"Untitled production"} status={`${props.initialStatus} • ${formatSecondsLabel(Math.round(totalMs/1000))}`} pills={<><GlassBadge tone="default">Preflight {preflight.score}</GlassBadge><GlassBadge tone={preflight.blockers.length?"copper":"default"}>{preflight.blockers.length?"Needs fixes":"Render ready"}</GlassBadge></>} actions={<><GlassButton variant="ghost" onClick={()=>void saveDraft()}>{isSaving?"Saving...":"Save"}</GlassButton><GlassButton variant="secondary" onClick={()=>void renderAgain()}>{isRendering?"Queueing...":"Render"}</GlassButton><Link href={`/shopreel/review/${props.generationId}`}><GlassButton variant="ghost">Review</GlassButton></Link></>} />}
  mediaRail={<SourceMediaRail><MediaBin items={props.mediaItems} /><SceneSequenceCard><div className="text-xs text-white/70">Reusable assets and source clips live here. Add media before final render.</div></SceneSequenceCard></SourceMediaRail>}
  stage={<CinematicPreviewStage><div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_260px]"><div className="rounded-3xl border border-white/10 bg-black/70 p-3">{props.initialRenderUrl?<video src={props.initialRenderUrl} controls className="aspect-[9/16] w-full rounded-2xl object-cover"/>:<div className="flex aspect-[9/16] items-center justify-center rounded-2xl border border-dashed border-white/20 text-sm text-white/60">No render preview yet.</div>}</div><div className="space-y-3"><PlatformPreviewCard label="Active scene"><div className="text-sm text-white">{selectedScene?.title??"No scene"}</div><div className="text-xs text-white/70">{selectedScene?.role} • {selectedScene?.durationSeconds ?? 0}s</div></PlatformPreviewCard><PlatformPreviewCard label="Output framing"><div className="aspect-[9/16] rounded-xl border border-white/10 bg-white/5"/></PlatformPreviewCard><PlatformPreviewCard label="Pacing"><div className="text-xs text-white/70">Hook / Body / CTA pacing visible in timeline rail.</div></PlatformPreviewCard></div></div></CinematicPreviewStage>}
  inspector={<InspectorRail><GlassCard label="Inspector" title="Scene metadata"><GlassInput label="Project title" value={draft.title} onChange={(e)=>setDraft(p=>syncDraft({...p,title:e.target.value}))} />{selectedScene?<><GlassInput label="Scene title" value={selectedScene.title} onChange={(e)=>execCommand({type:"scene.update",sceneId:selectedScene.id,patch:{title:e.target.value}})} /><GlassTextarea label="Overlay" value={selectedScene.overlayText??""} onChange={(e)=>execCommand({type:"caption.update",sceneId:selectedScene.id,caption:e.target.value})} /><GlassTextarea label="Voiceover" value={selectedScene.voiceoverText??""} onChange={(e)=>execCommand({type:"audio.update",sceneId:selectedScene.id,voiceover:e.target.value})} /></>:null}</GlassCard><RenderReadinessRail><div className="text-sm text-white">Render readiness</div><div className="text-xs text-white/70">{preflight.blockers.length?preflight.blockers.map(b=>b.message).join("; "):"No blockers."}</div><div className="mt-2 flex gap-2"><GlassButton variant="ghost" onClick={undoCommand} disabled={historyPointer<=0}>Undo</GlassButton><GlassButton variant="ghost" onClick={redoCommand} disabled={!historyStack[historyPointer+1]}>Redo</GlassButton></div></RenderReadinessRail><RenderReadinessRail><div className="text-xs text-white/70">AI suggestions and handoff checklist remain manual + operator controlled in this pass.</div><div className="text-xs text-white/60">Last command: {summarizeCommand(commandHistory.at(-1)?.type??"scene.update")}. Save: {saveState}.</div>{error?<div className="text-xs text-amber-300">{error}</div>:null}</RenderReadinessRail></InspectorRail>}
  timeline={<SequenceTimeline><div className="overflow-x-auto"><div className="min-w-[980px] space-y-3"><TimelineRuler durationMs={totalMs}/>{(["video","overlay","voiceover","subtitles"] as const).map((lane)=><TimelineLane key={lane} label={lane} lane={lane} clips={clips} selectedClipId={selectedClip?.id??null} onSelectClip={(clipId,_sceneId,l)=>setSelection({type:"clip",id:clipId,lane:l})} onDragScene={(sceneId,delta)=>Math.abs(delta)>=PX_PER_SECOND && execCommand({type:"scene.reorder",sceneId,direction:delta>0?1:-1})} onResizeScene={(sceneId,delta)=>execCommand({type:"scene.update",sceneId,patch:{durationSeconds:Math.max(1,Number(selectedScene?.durationSeconds??3)+Math.round(delta/PX_PER_SECOND))}})} />)}</div></div></SequenceTimeline>}
 />;
}
